/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, {Component} from 'react';
import {StyleSheet, Text, View} from 'react-native';
import ImageColors from 'react-native-image-colors';

export default class App extends Component {
  URL = 'https://i.imgur.com/O3XSdU7.jpg';

  state = {
    status: 'starting',
    colors: null,
  };

  componentDidMount() {
    this.fetchColors();
  }

  fetchColors = async () => {
    const colors = await ImageColors.getImageColorsFromURL(this.URL, {
      getDominant: true,
      getAverage: true,
      getVibrant: true,
      getDarkVibrant: true,
      getLightVibrant: true,
      getDarkMuted: true,
      getLightMuted: true,
      getMuted: true,
      defaultColor: '#000000',
    });

    this.setState({colors, status: 'DONE'});
  };
  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>☆ImageColors example☆</Text>
        <Text style={styles.instructions}>STATUS: {this.state.status}</Text>
        <Text style={styles.welcome}>☆NATIVE CALLBACK MESSAGE☆</Text>
        <Text style={styles.instructions}>
          {JSON.stringify(this.state.colors)}
        </Text>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
    marginHorizontal: 10,
  },
});
